# Generated by Django 4.0.1 on 2022-01-30 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_patient_profile_pic'),
        ('patients', '0004_threadmodel_messagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labtest_Date_Time', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('report', models.FileField(null=True, upload_to='static/patientLabreport')),
                ('booked_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
    ]
