# Generated by Django 4.0.1 on 2022-01-31 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_labtest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='report',
        ),
    ]
