# Generated by Django 3.2.6 on 2022-01-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='booked_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
