# Generated by Django 4.0.1 on 2022-01-31 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_labtest_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(null=True, upload_to='static/patientLabreport')),
                ('uploadeddate', models.DateTimeField(auto_now_add=True, null=True)),
                ('labtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.labtest')),
            ],
        ),
    ]
