# Generated by Django 4.0.1 on 2022-02-01 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20220125_1546'),
        ('patients', '0008_labtest_report_delete_labreport'),
    ]

    operations = [
    ]
