# Generated by Django 3.2.6 on 2022-01-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='medicine_image',
            field=models.FileField(null=True, upload_to='static/medicine_uploads'),
        ),
    ]
