# Generated by Django 3.2.9 on 2021-12-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='deptPic',
            field=models.FileField(default='static/default_user.png', upload_to='static/profile'),
        ),
    ]
