# Generated by Django 3.2.9 on 2021-12-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctorprofile_patientprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='username',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='username',
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='profile_pic',
            field=models.FileField(default='static/default_user.png', upload_to='static/doctorProfile'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_pic',
            field=models.FileField(default='static/default_user.png', upload_to='static/patientProfile'),
        ),
    ]
