# Generated by Django 3.2.6 on 2022-01-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220102_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.FileField(default='static/default_user.png', null=True, upload_to='static/patientProfile'),
        ),
    ]
